import type { Post } from '@/types/post'
import { POST_CSV_COLUMNS, POST_CSV_HEADERS } from '@/types/post'

export { POST_CSV_HEADERS }

/** CSV行（ヘッダー除く）をPostオブジェクトに変換 */
export function rowToPost(row: string[]): Post {
  const col = POST_CSV_COLUMNS
  return {
    title: row[col.title] ?? '',
    genre: row[col.genre] ?? '',
    area: row[col.area] ?? '',
    schoolName: row[col.schoolName] ?? '',
    clubName: row[col.clubName] ?? '',
    companyName: row[col.companyName] ?? '',
    videoCategory: row[col.videoCategory] ?? '',
    careerCategory: row[col.careerCategory] ?? '',
    recruitmentInfo: row[col.recruitmentInfo] ?? '',
    instagramUrl: row[col.instagramUrl] ?? '',
    imageUrl: row[col.imageUrl] ?? '',
    description: row[col.description] ?? '',
    date: row[col.date] ?? '',
  }
}

/** PostオブジェクトをCSV行に変換（スプレッドシート書き出し用） */
export function postToRow(post: Post): string[] {
  return POST_CSV_HEADERS.map((header) => {
    switch (header) {
      case '投稿タイトル': return post.title
      case 'ジャンル': return post.genre
      case 'エリア': return post.area
      case '学校名': return post.schoolName
      case '部活名': return post.clubName
      case '企業名': return post.companyName
      case '動画カテゴリ': return post.videoCategory
      case '進路カテゴリ': return post.careerCategory
      case '募集情報': return post.recruitmentInfo
      case 'InstagramURL': return post.instagramUrl
      case '画像URL': return post.imageUrl
      case '説明文': return post.description
      case '投稿日': return post.date
    }
  })
}

/** 開発・CSV未設定時のダミーデータ（20件） */
export const DUMMY_POSTS: Post[] = [
  {
    title: '札幌南高校 吹奏楽部の日常',
    genre: '部活',
    area: '札幌',
    schoolName: '札幌南高校',
    clubName: '吹奏楽部',
    companyName: '',
    videoCategory: '部活紹介',
    careerCategory: '音楽・芸術',
    recruitmentInfo: '新入部員募集中',
    instagramUrl: 'https://www.instagram.com/p/example01/',
    imageUrl: 'https://picsum.photos/seed/sapporo01/400/400',
    description: 'コンクールに向けて練習に励む吹奏楽部の姿を紹介します。',
    date: '2026/01/15',
  },
  {
    title: '旭川永嶺高校 サッカー部 全国大会出場',
    genre: '部活',
    area: '旭川',
    schoolName: '旭川永嶺高校',
    clubName: 'サッカー部',
    companyName: '',
    videoCategory: '大会ハイライト',
    careerCategory: 'スポーツ',
    recruitmentInfo: '',
    instagramUrl: 'https://www.instagram.com/p/example02/',
    imageUrl: 'https://picsum.photos/seed/asahikawa02/400/400',
    description: '北海道大会優勝！全国大会出場を果たしたサッカー部の活躍。',
    date: '2026/01/20',
  },
  {
    title: '函館ラ・サール高校 探究学習の取り組み',
    genre: '学校',
    area: '函館',
    schoolName: '函館ラ・サール高校',
    clubName: '',
    companyName: '',
    videoCategory: '学校紹介',
    careerCategory: '進学',
    recruitmentInfo: 'オープンスクール開催中',
    instagramUrl: 'https://www.instagram.com/p/example03/',
    imageUrl: 'https://picsum.photos/seed/hakodate03/400/400',
    description: '地域課題に取り組む探究学習プログラムをご紹介。',
    date: '2026/02/01',
  },
  {
    title: 'キリンビール 函館工場見学',
    genre: '企業訪問',
    area: '函館',
    schoolName: '函館商業高校',
    clubName: '',
    companyName: 'キリンビール',
    videoCategory: '企業訪問',
    careerCategory: '製造・ものづくり',
    recruitmentInfo: '工場見学受付中',
    instagramUrl: 'https://www.instagram.com/p/example04/',
    imageUrl: 'https://picsum.photos/seed/kirin04/400/400',
    description: 'ビール醸造の工程と品質管理の現場を見学しました。',
    date: '2026/02/05',
  },
  {
    title: '釧路鶴野高校 バスケットボール部',
    genre: '部活',
    area: '釧路',
    schoolName: '釧路鶴野高校',
    clubName: 'バスケットボール部',
    companyName: '',
    videoCategory: '部活紹介',
    careerCategory: 'スポーツ',
    recruitmentInfo: '体験入部受付中',
    instagramUrl: 'https://www.instagram.com/p/example05/',
    imageUrl: 'https://picsum.photos/seed/kushiro05/400/400',
    description: '朝練から始まるバスケ部の一日に密着。',
    date: '2026/02/10',
  },
  {
    title: '帯広柏葉高校 農業科の実習風景',
    genre: '学校',
    area: '帯広',
    schoolName: '帯広柏葉高校',
    clubName: '',
    companyName: '',
    videoCategory: '学校紹介',
    careerCategory: '農業・食品',
    recruitmentInfo: '',
    instagramUrl: 'https://www.instagram.com/p/example06/',
    imageUrl: 'https://picsum.photos/seed/obihiro06/400/400',
    description: '十勝の大地で学ぶ農業科の実習と研究活動。',
    date: '2026/02/15',
  },
  {
    title: '日本ハム 帯広工場 見学レポート',
    genre: '企業訪問',
    area: '帯広',
    schoolName: '帯広農業高校',
    clubName: '',
    companyName: '日本ハム',
    videoCategory: '企業訪問',
    careerCategory: '食品・農業',
    recruitmentInfo: '夏のインターン募集',
    instagramUrl: 'https://www.instagram.com/p/example07/',
    imageUrl: 'https://picsum.photos/seed/nipponham07/400/400',
    description: 'ハム・ソーセージ製造ラインと品質検査の現場。',
    date: '2026/02/20',
  },
  {
    title: '北見藤高校 科学部 ロケットプロジェクト',
    genre: '部活',
    area: '北見',
    schoolName: '北見藤高校',
    clubName: '科学部',
    companyName: '',
    videoCategory: '部活紹介',
    careerCategory: '理系・工学',
    recruitmentInfo: '',
    instagramUrl: 'https://www.instagram.com/p/example08/',
    imageUrl: 'https://picsum.photos/seed/kitami08/400/400',
    description: '自作ロケットの設計から打ち上げまでの挑戦記。',
    date: '2026/03/01',
  },
  {
    title: '小樽商科大学附属高校 国際交流',
    genre: '学校',
    area: '小樽',
    schoolName: '小樽商科大学附属高校',
    clubName: '',
    companyName: '',
    videoCategory: '学校紹介',
    careerCategory: '国際・語学',
    recruitmentInfo: '説明会実施中',
    instagramUrl: 'https://www.instagram.com/p/example09/',
    imageUrl: 'https://picsum.photos/seed/otaru09/400/400',
    description: '海外姉妹校とのオンライン交流プログラム。',
    date: '2026/03/05',
  },
  {
    title: '苫小牧東高校 柔道部 インターハイ出場',
    genre: '部活',
    area: '苫小牧',
    schoolName: '苫小牧東高校',
    clubName: '柔道部',
    companyName: '',
    videoCategory: '大会ハイライト',
    careerCategory: 'スポーツ',
    recruitmentInfo: '新入部員歓迎',
    instagramUrl: 'https://www.instagram.com/p/example10/',
    imageUrl: 'https://picsum.photos/seed/tomakomai10/400/400',
    description: 'インターハイ出場を目指す柔道部の厳しい稽古風景。',
    date: '2026/03/10',
  },
  {
    title: '北海道電力 苫小牧火力発電所',
    genre: '企業訪問',
    area: '苫小牧',
    schoolName: '苫小牧工業高校',
    clubName: '',
    companyName: '北海道電力',
    videoCategory: '企業訪問',
    careerCategory: 'エネルギー',
    recruitmentInfo: '見学ツアー受付中',
    instagramUrl: 'https://www.instagram.com/p/example11/',
    imageUrl: 'https://picsum.photos/seed/hepco11/400/400',
    description: '地域の電力を支える火力発電所の見学記。',
    date: '2026/03/15',
  },
  {
    title: '札幌北高校 美術部 卒業制作展',
    genre: '部活',
    area: '札幌',
    schoolName: '札幌北高校',
    clubName: '美術部',
    companyName: '',
    videoCategory: '部活紹介',
    careerCategory: '美術・デザイン',
    recruitmentInfo: '',
    instagramUrl: 'https://www.instagram.com/p/example12/',
    imageUrl: 'https://picsum.photos/seed/sapporokita12/400/400',
    description: '卒業制作展に出品された作品の数々を紹介。',
    date: '2026/03/20',
  },
  {
    title: '札幌大学附属高校 進路支援プログラム',
    genre: '学校',
    area: '札幌',
    schoolName: '札幌大学附属高校',
    clubName: '',
    companyName: '',
    videoCategory: '学校紹介',
    careerCategory: '進学',
    recruitmentInfo: '個別相談受付中',
    instagramUrl: 'https://www.instagram.com/p/example13/',
    imageUrl: 'https://picsum.photos/seed/sapporodai13/400/400',
    description: '大学進学に向けた個別面談とキャリア教育。',
    date: '2026/03/25',
  },
  {
    title: 'ソフトバンク 札幌オフィス見学',
    genre: '企業訪問',
    area: '札幌',
    schoolName: '札幌創成高校',
    clubName: '',
    companyName: 'ソフトバンク',
    videoCategory: '企業訪問',
    careerCategory: 'IT・通信',
    recruitmentInfo: 'IT体験ワークショップ開催',
    instagramUrl: 'https://www.instagram.com/p/example14/',
    imageUrl: 'https://picsum.photos/seed/softbank14/400/400',
    description: '5GやAIの最新技術を体験できるオフィスツアー。',
    date: '2026/04/01',
  },
  {
    title: '旭川龍谷高校 バレーボール部',
    genre: '部活',
    area: '旭川',
    schoolName: '旭川龍谷高校',
    clubName: 'バレーボール部',
    companyName: '',
    videoCategory: '部活紹介',
    careerCategory: 'スポーツ',
    recruitmentInfo: '春の体験会あり',
    instagramUrl: 'https://www.instagram.com/p/example15/',
    imageUrl: 'https://picsum.photos/seed/asahikawaryu15/400/400',
    description: 'チームワークを大切にするバレー部の練習風景。',
    date: '2026/04/05',
  },
  {
    title: '旭川医療大学 看護学科見学',
    genre: '企業訪問',
    area: '旭川',
    schoolName: '旭川北高校',
    clubName: '',
    companyName: '旭川医療大学',
    videoCategory: '企業訪問',
    careerCategory: '医療・福祉',
    recruitmentInfo: 'オープンキャンパス開催',
    instagramUrl: 'https://www.instagram.com/p/example16/',
    imageUrl: 'https://picsum.photos/seed/asahikawa-med16/400/400',
    description: 'シミュレーション室での看護実習体験。',
    date: '2026/04/10',
  },
  {
    title: '釧路江南高校 茶道部 文化祭',
    genre: '部活',
    area: '釧路',
    schoolName: '釧路江南高校',
    clubName: '茶道部',
    companyName: '',
    videoCategory: '部活紹介',
    careerCategory: '伝統文化',
    recruitmentInfo: '',
    instagramUrl: 'https://www.instagram.com/p/example17/',
    imageUrl: 'https://picsum.photos/seed/kushiro17/400/400',
    description: '文化祭でお茶席を開催した茶道部の様子。',
    date: '2026/04/15',
  },
  {
    title: '帯広三条高校 馬術部 十勝の草原',
    genre: '部活',
    area: '帯広',
    schoolName: '帯広三条高校',
    clubName: '馬術部',
    companyName: '',
    videoCategory: '部活紹介',
    careerCategory: 'スポーツ',
    recruitmentInfo: '見学随時受付',
    instagramUrl: 'https://www.instagram.com/p/example18/',
    imageUrl: 'https://picsum.photos/seed/obihiro18/400/400',
    description: '十勝の大自然で馬と向き合う馬術部の活動。',
    date: '2026/04/20',
  },
  {
    title: 'ロイズ 北見チョコレート工場',
    genre: '企業訪問',
    area: '北見',
    schoolName: '北見商業高校',
    clubName: '',
    companyName: 'ロイズ',
    videoCategory: '企業訪問',
    careerCategory: '食品・製菓',
    recruitmentInfo: '工場見学予約受付中',
    instagramUrl: 'https://www.instagram.com/p/example19/',
    imageUrl: 'https://picsum.photos/seed/royce19/400/400',
    description: 'チョコレート製造工程と品質管理の見学ツアー。',
    date: '2026/04/25',
  },
  {
    title: '小樽潮陵高校 合唱部 全国コンクール',
    genre: '部活',
    area: '小樽',
    schoolName: '小樽潮陵高校',
    clubName: '合唱部',
    companyName: '',
    videoCategory: '大会ハイライト',
    careerCategory: '音楽・芸術',
    recruitmentInfo: '新入部員募集中',
    instagramUrl: 'https://www.instagram.com/p/example20/',
    imageUrl: 'https://picsum.photos/seed/otarucho20/400/400',
    description: '全国コンクール出場を目指す合唱部のハーモニー。',
    date: '2026/05/01',
  },
]
